# Generated by Django 4.2.7 on 2024-02-20 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0014_hash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hash',
        ),
    ]
