# Generated by Django 4.2.7 on 2023-12-20 20:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_rename_auctioncategories_categories_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AuctionListings",
            new_name="AuctionListing",
        ),
        migrations.RenameModel(
            old_name="Categories",
            new_name="Category",
        ),
    ]
