# Generated by Django 4.2.7 on 2023-12-22 01:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_remove_auctionlisting_bid_count_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auctionlisting",
            old_name="image_url",
            new_name="imageurl",
        ),
        migrations.RenameField(
            model_name="auctionlisting",
            old_name="owner",
            new_name="user",
        ),
    ]
