# Generated by Django 4.2.7 on 2023-12-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_remove_auctionlisting_user_auctionlisting_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="imageurl",
            field=models.CharField(max_length=10000),
        ),
    ]
