# Generated by Django 4.2.7 on 2023-12-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_alter_auctionlisting_imageurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
