# Generated by Django 4.2.7 on 2023-12-23 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0013_alter_auctionlisting_watchlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="user",
        ),
        migrations.AddField(
            model_name="comments",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comments",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing",
                to="auctions.auctionlisting",
            ),
        ),
    ]
