# Generated by Django 4.2.7 on 2023-12-24 00:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0014_remove_comments_user_comments_author_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comments",
            new_name="Comment",
        ),
    ]
