# Generated by Django 4.2.7 on 2023-12-24 01:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0015_rename_comments_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comment",
            new_name="message",
        ),
    ]
