# Generated by Django 4.2.7 on 2023-12-24 01:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0016_rename_comment_comment_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="commentDate",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
