# Generated by Django 4.2.7 on 2023-12-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0020_alter_bid_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="bid",
            field=models.FloatField(default=0),
        ),
    ]
