# Generated by Django 4.2.7 on 2023-12-27 01:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0021_alter_bid_bid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auctionlisting",
            old_name="is_active",
            new_name="isActive",
        ),
    ]
