# Generated by Django 4.2.7 on 2023-12-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0023_bid_bidcount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bid",
            name="bidCount",
        ),
        migrations.AddField(
            model_name="auctionlisting",
            name="bidCount",
            field=models.IntegerField(default=0),
        ),
    ]
