# Generated by Django 4.2.7 on 2023-12-29 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0024_remove_bid_bidcount_auctionlisting_bidcount"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="userWatchlist", to="auctions.auctionlisting"
            ),
        ),
        migrations.AlterField(
            model_name="auctionlisting",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="auctionWatchlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
