# Generated by Django 4.2.7 on 2023-12-29 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0025_user_watchlist_alter_auctionlisting_watchlist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auctionlisting",
            old_name="creation_date",
            new_name="closingDate",
        ),
        migrations.AddField(
            model_name="auctionlisting",
            name="creationDate",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
