# Generated by Django 4.2.7 on 2023-12-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0026_rename_creation_date_auctionlisting_closingdate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="closingDate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
