# Generated by Django 5.0.2 on 2024-02-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capstone", "0010_contact_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="timeline",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
