# Generated by Django 5.0.2 on 2024-02-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capstone", "0011_alter_referral_id_alter_timeline_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="timeline",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
