name: Django CI - Final Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Create Virtual Environment
        run: python -m venv venv && source venv/bin/activate

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          pip install -r "Final Project/Capstone/project5/requirements.txt"

      - name: Install unzip
        run: sudo apt-get install unzip

      - name: Remove existing Chromedriver
        run: sudo rm /usr/bin/chromedriver || true

      - name: Download ChromeDriver
        run: |
          CHROMEDRIVER_VERSION=114.0.5735.90
          wget -q "https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip"
          unzip -o chromedriver_linux64.zip -d ./chromedriver
          export PATH=$PATH:$PWD/chromedriver

      - name: Debugging Info
        run: |
          echo "Current directory: $PWD"
          echo "Contents of current directory: $(ls -l)"

      - name: Run Tests
        run: |
          cd "Final Project/Capstone/project5"
          python manage.py test
